spring.application.name=sql-task-app

# PostgreSQL DataSource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sqltaskdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:tasukuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:taskpass}
spring.datasource.driver-class-name=org.postgresql.Driver

# Schema & Data initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# Server port
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
